apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: nginx-main 
spec:
  selector:
    matchLabels:
      app: nginx # has to match .spec.template.metadata.labels
  serviceName: "nginx"
  replicas: 1 
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: k8s.gcr.io/nginx-slim:0.8 
        ports:
        - containerPort: 80
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /
            port: 80
            scheme: HTTP
          initialDelaySeconds: 1
          periodSeconds: 120
          successThreshold: 1
          timeoutSeconds: 5
      - name: nginx2
        image: k8s.gcr.io/nginx-slim:0.8 
        ports:
        - containerPort: 8080
