apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    client: encode
    environment: production
    system: webapp1
  name: workflow
  annotations:
    argocd.argoproj.io/hook: PreSync
    argocd.argoproj.io/sync-wave: "-1"
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  labels:
    client: encode
    environment: production
    system: webapp1
  name: workflow-admin
  annotations:
    argocd.argoproj.io/hook: PreSync
    argocd.argoproj.io/sync-wave: "-1"
rules:
- apiGroups:
  - '*'
  resources:
  - '*'
  verbs:
  - '*'

