apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    client: encode
    environment: production
    system: webapp1
  name: workflow
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  labels:
    client: encode
    environment: production
    system: webapp1
  name: workflow-admin
rules:
- apiGroups:
  - '*'
  resources:
  - '*'
  verbs:
  - '*'

